name: Ellen Beier
favicon: null
layout_spectrum: 1
typography_spectrum: 0.31554
title: Illustrator
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cabaa1'
    - '#9b8d64'
    - '#d64637'
    - '#2a3d3b'
    - '#7c5e33'
  brandStrength: 0.1875
  lightness: 0.8155915311072022
  saturation: 0.4375
  rhythmicContrast: 0.5
purpose: []
